Build pre-installed adsb.im ready images
- allow dietpi-software to run preinstall

- dietpi-build: add sizeincrement option to make the root partition
  bigger when preinstalling software

- dietpi-software: don't run the post install automation on preinstall

- ensure preinstalled packages aren't auto-removed

- suppress incorrect shellcheck warnings

- explicitly require initramfs-tools for native build

- running this on GitHub requires the IPv4 test workaround

- don't compress preinstalled images
  Running xz takes forever and when we use this to create adsb.im
  images, the next step would just have to uncompress this image again.
  So let's just not compress this in the first place. And then of course
  don't delete the image at the end, either...

- don't fail if you can't delete a file

- create custom 141 pre-install script

- reduce number of times apt update is called on first boot

Signed-off-by: Dirk Hohndel <dirk@hohndel.org>

diff --git a/.build/images/dietpi-build b/.build/images/dietpi-build
--- a/.build/images/dietpi-build
+++ b/.build/images/dietpi-build
@@ -63,6 +63,8 @@ RK35XX_MAINLINE=0
 # initial rootfs size override. dietpi-imager will shrink it as much as possible, but the larger the initial rootfs size, the larger the resulting image.
 # See "root_size" below for per-SBC defaults, which may not work with all combinations of options, and are updated regularly.
 ROOT_SIZE=
+PREINST=()
+SIZE_INCREMENT=0
 while (( $# ))
 do
 	case $1 in
@@ -84,6 +86,8 @@ do
 		'--test-uboot') TEST_UBOOT=1;;
 		'--root-size') shift; ROOT_SIZE=$1;;
 		'--rk35xx-mainline') RK35XX_MAINLINE=1;;
+		'--preinst') shift; PREINST+=("$1");;
+		'--sizeincrement') shift; SIZE_INCREMENT=$1;;
 		*) Error_Exit "Invalid input \"$1\"";;
 	esac
 	shift
@@ -213,8 +217,16 @@ case $PTTYPE in
 	*) Error_Exit "Invalid partition table type \"$PTTYPE\" passed";;
 esac
 
+# Make sure we add space that was requested on the command line
+((root_size+=$SIZE_INCREMENT))
+
+# Do not add trailing FAT partitions for VM, container and (Clonezilla) installer images, and if there is a boot FAT partition already
+[[ $HW_MODEL == 20 || $HW_MODEL == 75 || $ITYPE == 'Installer' ]] && ADD_DOS_PART=0
+[[ $boot_size -gt 0 && $boot_fstype == 'fat'* ]] && ADD_DOS_PART=0
+
 # Check for valid root filesystem type and set variables accordingly
 fsname='' afspackages=() afs_opts=() afsck=() aresize=() apackages=()
+
 case $FSTYPE in
 	'ext4') afspackages+=('e2fsprogs') afs_opts=('-e' 'remount-ro' '-O' '^has_journal') afsck=('e2fsck' '-fyD') aresize=('resize2fs');;
 	'f2fs') fsname='F2FS' afspackages+=('f2fs-tools') afsck=('fsck.f2fs' '-f') aresize=('resize.f2fs'); uname -r | grep -q '-azure$' && apackages+=("linux-modules-extra-$(uname -r)");;
@@ -281,7 +293,7 @@ G_EXIT_CUSTOM(){
 	findmnt -M "$FP_ORIGIN/rootfs" &> /dev/null && G_EXEC umount -R "$FP_ORIGIN/rootfs"
 	[[ -d $FP_ORIGIN/rootfs ]] && G_EXEC rmdir "$FP_ORIGIN/rootfs"
 	[[ $FP_LOOP ]] && losetup "$FP_LOOP" &> /dev/null && G_EXEC losetup -d "$FP_LOOP"
-	[[ -f $OUTPUT_IMG_NAME.img ]] && G_EXEC rm "$OUTPUT_IMG_NAME.img"
+	[[ $SKIP_ARCHIVE = 0 ]] && [[ -f $OUTPUT_IMG_NAME.img ]] && G_EXEC rm "$OUTPUT_IMG_NAME.img"
 }
 
 # Create image file
@@ -417,12 +429,16 @@ IFS=, packages+=${afspackages[*]}; unset -v IFS
 [[ $HW_MODEL == 75 ]] && packages+=',iproute2' || packages+=',console-setup,dropbear,ethtool,fake-hwclock,ifupdown,isc-dhcp-client,kmod,rfkill,systemd-timesyncd,usbutils'
 [[ $HW_MODEL =~ ^(20|75)$ ]] || packages+=',iw,wireless-tools,wpasupplicant,wireless-regdb'
 # Add temporary tmpfs mounts to prevent certain files created by debootstrap being written to disk
-# - tmpfs mounts have 1777 mode by default.
-G_EXEC mount -m -t tmpfs tmpfs rootfs/dev
-G_EXEC mount -m -t tmpfs tmpfs rootfs/run
-G_EXEC mount -m -t tmpfs tmpfs rootfs/var/cache/apt
-G_EXEC mount -m -t tmpfs tmpfs rootfs/var/lib/apt/lists
-G_EXEC mount -m -t tmpfs tmpfs rootfs/var/log
+# - "-o X-mount.mkdir" has a shortcut "-m" in recent "mount", but not available on Ubuntu Jammy yet!
+G_EXEC mount -o X-mount.mkdir -t tmpfs tmpfs rootfs/dev
+G_EXEC mount -o X-mount.mkdir -t tmpfs tmpfs rootfs/run
+G_EXEC mount -o X-mount.mkdir -t tmpfs tmpfs rootfs/var/cache/apt
+G_EXEC mount -o X-mount.mkdir -t tmpfs tmpfs rootfs/var/lib/apt/lists
+G_EXEC mount -o X-mount.mkdir -t tmpfs tmpfs rootfs/var/log
+packages='apt,bash-completion,bzip2,ca-certificates,cron,curl,fdisk,gpg,htop,iputils-ping,locales,mawk,nano,parted,procps,psmisc,sudo,systemd-sysv,tzdata,udev,unzip,wget,whiptail,'
+(( $DISTRO > 7 )) && packages+='7zip,' || packages+='p7zip,'
+[[ $HW_MODEL == 21 ]] && packages+='initramfs-tools,zstd,'
+[[ $HW_MODEL == 75 ]] && packages+='iproute2' || packages+='console-setup,dropbear,ethtool,fake-hwclock,ifupdown,isc-dhcp-client,kmod,rfkill,systemd-timesyncd,usbutils'
 # - "--skip=check/empty" to ignore /etc/fstab, boot and tmpfs mounts we added above
 # - "--skip=check/qemu" to skip arch test, which requires the "arch-test" package. We however assure emulation support our end.
 G_EXEC_OUTPUT=1 G_EXEC mmdebstrap --mode=root --format=dir --skip=check/empty,check/qemu --variant=apt --include="$packages" --arch="$parch" --keyring="$keyring" "$distro" ./rootfs "${mirrors[@]}"
@@ -471,7 +487,13 @@ cat << _EOF_ > rootfs/etc/rc.local
 #!/bin/dash
 {
 infocmp "\$TERM" > /dev/null 2>&1 || { echo "[ WARN ] Unsupported TERM=\"\$TERM\", switching to TERM=\"dumb\""; export TERM=dumb; }
+echo '[ INFO ] Running DietPi-Installer...'
+cat /etc/rc.local
+_EOF_
+
+cat << _EOF_ >> rootfs/etc/rc.local
 export GITOWNER='$GITOWNER' GITBRANCH='$GITBRANCH' HW_MODEL='$HW_MODEL' IMAGE_CREATOR=0 PREIMAGE_INFO=0 WIFI_REQUIRED=1 DISTRO_TARGET=$DISTRO TEST_KERNEL=$TEST_KERNEL TEST_UBOOT=$TEST_UBOOT RK35XX_MAINLINE=$RK35XX_MAINLINE TMPDIR='/tmp'
+
 echo '[ INFO ] Running DietPi-Installer for $G_GITOWNER/$G_GITBRANCH'
 bash -c "\$(curl -sSf 'https://raw.githubusercontent.com/$G_GITOWNER/DietPi/$G_GITBRANCH/.build/images/dietpi-installer')" || { echo '[FAILED] DietPi-Installer failed, shutting down ...'; journalctl -n 25; df -h; free -h; systemctl start poweroff.target; exit 1; }
 > /success
@@ -480,6 +502,16 @@ exit 0
 } > /dev/console 2>&1 < /dev/console
 _EOF_
 G_EXEC chmod +x rootfs/etc/rc.local
+
+cat << _EOF_ > rootfs/etc/dietpi-preinst-packages
+#!/bin/dash
+[ ${#PREINST[@]} != 0 ] || exit 0
+echo "[ INFO ] preinstalling ${PREINST[@]}"
+# Workaround for failing IPv4 network connectivity check as GitHub Actions runners do not receive external ICMP echo replies.
+sed -i 's/CONFIG_CHECK_CONNECTION_IP=.*/CONFIG_CHECK_CONNECTION_IP=127.0.0.1/' /boot/dietpi.txt
+G_DISTRO="$DISTRO" G_DISTRO_NAME="$distro" G_HW_ARCH="$G_HW_ARCH" G_HW_MODEL="${HW_MODEL%.*}" /bin/bash /boot/dietpi/dietpi-software preinstall "${PREINST[@]}" || poweroff
+_EOF_
+G_EXEC chmod +x rootfs/etc/dietpi-preinst-packages
 
 # Start container
 # - Bind mounts required to allow container reading its own drive info, /dev/disk for GRUB and probably other tools to detect UUIDs
@@ -518,6 +550,9 @@ G_EXEC losetup -d "$FP_LOOP"
 # Do not add trailing FAT partition for VM, container and ISO installer images, and if there is a boot FAT partition already
 [[ $HW_MODEL =~ ^(20|75)$ || $VARIANT == 'iso' || ( $boot_size -gt 0 && $boot_fstype == 'vfat' ) ]] && ADD_DOS_PART=0
 export FP_ROOT_DEV CLONING_TOOL OUTPUT_IMG_NAME MOUNT_IT='Off' SKIP_FIRSTBOOT_RESIZE=1
+# if preinstalling things, we never want to waste the time on compressing the image
+[[ ${#PREINST[@]} != 0 ]] && SKIP_ARCHIVE=1
+export FP_ROOT_DEV CLONING_TOOL OUTPUT_IMG_NAME MOUNT_IT='Off' SKIP_ARCHIVE SKIP_FIRSTBOOT_RESIZE=1
 IMAGER_ARGS=("$OUTPUT_IMG_NAME.img")
 (( $SKIP_ARCHIVE )) && IMAGER_ARGS+=('--skip-archive')
 [[ $UPLOAD_SCRIPT ]] && IMAGER_ARGS+=('--upload-script' "$UPLOAD_SCRIPT")
