Build pre-installed adsb.im ready images
- allow dietpi-software to run preinstall

- dietpi-build: add sizeincrement option to make the root partition
  bigger when preinstalling software

- dietpi-software: don't run the post install automation on preinstall

- ensure preinstalled packages aren't auto-removed

- suppress incorrect shellcheck warnings

- explicitly require initramfs-tools for native build

- running this on GitHub requires the IPv4 test workaround

- don't compress preinstalled images
  Running xz takes forever and when we use this to create adsb.im
  images, the next step would just have to uncompress this image again.
  So let's just not compress this in the first place. And then of course
  don't delete the image at the end, either...

- don't fail if you can't delete a file

- create custom 141 pre-install script

- reduce number of times apt update is called on first boot

Signed-off-by: Dirk Hohndel <dirk@hohndel.org>

diff --git a/.build/images/dietpi-build b/.build/images/dietpi-build
--- a/.build/images/dietpi-build
+++ b/.build/images/dietpi-build
@@ -57,6 +57,8 @@ ADD_DOS_PART=1
 SIGN_PASS=
 TEST_KERNEL=0
 TEST_UBOOT=0
+PREINST=()
+SIZE_INCREMENT=0
 while (( $# ))
 do
 	case $1 in
@@ -75,6 +77,8 @@ do
 		'--sign') shift; SIGN_PASS=$1;;
 		'--test-kernel') TEST_KERNEL=1;;
 		'--test-uboot') TEST_UBOOT=1;;
+		'--preinst') shift; PREINST+=("$1");;
+		'--sizeincrement') shift; SIZE_INCREMENT=$1;;
 		*) G_DIETPI-NOTIFY 1 "Invalid input \"$1\", aborting..."; exit 1;;
 	esac
 	shift
@@ -193,6 +197,9 @@ case $PTTYPE in
 	*) G_DIETPI-NOTIFY 1 "Invalid partition table type \"$PTTYPE\" passed, aborting..."; exit 1;;
 esac
 
+# Make sure we add space that was requested on the command line
+((root_size+=$SIZE_INCREMENT))
+
 # Do not add trailing FAT partitions for VM, container and (Clonezilla) installer images, and if there is a boot FAT partition already
 [[ $HW_MODEL == 20 || $HW_MODEL == 75 || $ITYPE == 'Installer' ]] && ADD_DOS_PART=0
 [[ $boot_size -gt 0 && $boot_fstype == 'fat'* ]] && ADD_DOS_PART=0
@@ -269,7 +276,7 @@ G_EXIT_CUSTOM(){
 	findmnt -M "$FP_ORIGIN/rootfs" &> /dev/null && G_EXEC umount -R "$FP_ORIGIN/rootfs"
 	[[ -d $FP_ORIGIN/rootfs ]] && G_EXEC rmdir "$FP_ORIGIN/rootfs"
 	[[ $FP_LOOP ]] && losetup "$FP_LOOP" &> /dev/null && G_EXEC losetup -d "$FP_LOOP"
-	[[ -f $OUTPUT_IMG_NAME.img ]] && G_EXEC rm "$OUTPUT_IMG_NAME.img"
+	[[ $SKIP_ARCHIVE = 0 ]] && [[ -f $OUTPUT_IMG_NAME.img ]] && G_EXEC rm "$OUTPUT_IMG_NAME.img"
 }
 
 # Create image file
@@ -409,6 +416,7 @@ G_EXEC mount -o X-mount.mkdir -t tmpfs tmpfs rootfs/var/lib/apt/lists
 G_EXEC mount -o X-mount.mkdir -t tmpfs tmpfs rootfs/var/log
 packages='apt,bash-completion,bzip2,ca-certificates,cron,curl,fdisk,gpg,htop,iputils-ping,locales,mawk,nano,parted,procps,psmisc,sudo,systemd-sysv,tzdata,udev,unzip,wget,whiptail,'
 (( $DISTRO > 7 )) && packages+='7zip,' || packages+='p7zip,'
+[[ $HW_MODEL == 21 ]] && packages+='initramfs-tools,zstd,'
 [[ $HW_MODEL == 75 ]] && packages+='iproute2' || packages+='console-setup,dropbear,ethtool,fake-hwclock,ifupdown,isc-dhcp-client,kmod,rfkill,systemd-timesyncd,usbutils'
 # - "--skip=check/empty" to ignore /etc/fstab, boot and tmpfs mounts we added above
 # - "--skip=check/qemu" to skip arch test, which requires the "arch-test" package. We however assure emulation support out end.
@@ -426,6 +434,7 @@ cat << '_EOF_' > rootfs/etc/rc.local
 {
 infocmp "$TERM" > /dev/null 2>&1 || { echo "[ WARN ] Unsupported TERM=\"$TERM\", switching to TERM=\"dumb\""; export TERM=dumb; }
 echo '[ INFO ] Running DietPi-Installer...'
+cat /etc/rc.local
 _EOF_
 
 cat << _EOF_ >> rootfs/etc/rc.local
@@ -449,6 +458,16 @@ exit 0
 } > /dev/console 2>&1 < /dev/console
 _EOF_
 G_EXEC chmod +x rootfs/etc/rc.local
+
+cat << _EOF_ > rootfs/etc/dietpi-preinst-packages
+#!/bin/dash
+[ ${#PREINST[@]} != 0 ] || exit 0
+echo "[ INFO ] preinstalling ${PREINST[@]}"
+# Workaround for failing IPv4 network connectivity check as GitHub Actions runners do not receive external ICMP echo replies.
+sed -i 's/CONFIG_CHECK_CONNECTION_IP=.*/CONFIG_CHECK_CONNECTION_IP=127.0.0.1/' /boot/dietpi.txt
+G_DISTRO="$DISTRO" G_DISTRO_NAME="$distro" G_HW_ARCH="$G_HW_ARCH" G_HW_MODEL="${HW_MODEL%.*}" /bin/bash /boot/dietpi/dietpi-software preinstall "${PREINST[@]}" || poweroff
+_EOF_
+G_EXEC chmod +x rootfs/etc/dietpi-preinst-packages
 
 # Start container
 # - Bind mounts required to allow container reading its own drive info, /dev/disk for GRUB and probably other tools to detect UUIDs
@@ -475,6 +494,8 @@ G_EXEC losetup -d "$FP_LOOP"
 ##########################################
 # Do not pack and upload raw VM image if not explicitly requested
 [[ $VMTYPE && ! $VMTYPE =~ ^(raw|all)$ ]] && SKIP_ARCHIVE=1 || SKIP_ARCHIVE=0
+# if preinstalling things, we never want to waste the time on compressing the image
+[[ ${#PREINST[@]} != 0 ]] && SKIP_ARCHIVE=1
 export FP_ROOT_DEV CLONING_TOOL OUTPUT_IMG_NAME MOUNT_IT='Off' SKIP_ARCHIVE SKIP_FIRSTBOOT_RESIZE=1
 IMAGER_ARGS=("$OUTPUT_IMG_NAME.img")
 (( $ADD_DOS_PART )) && IMAGER_ARGS+=('--add-dos-part')
